# -*- coding: utf-8 -*-
"""Excel_RPA1.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/16-znriG8-5XKq_m6-KscBe6PKzOaTmrq

RPA 엑셀자동화 1. sheet생성과 test글자 입력
"""

from openpyxl import Workbook
wb=Workbook() #새 워크북생성
#ws=wb.active #현재활성화된 sheet가져옴
ws=wb.create_sheet() #새로열고 기본이름 사용
ws.title="Mysheet" #sheet이름 변경
ws.sheet_properties.tabColor="ff66ff" #RGB형태 값입력,tab 색상지정

#sheet,Mysheet,YourSheet
ws1 = wb.create_sheet("YourSheet") #주어진 이름으로 sheet생성
ws2 = wb.create_sheet("NewSheet",2) #2번재 index에 sheet생성
new_ws=wb["NewSheet"] #dictionary형태로 sheet에 접근
print(wb.sheetnames) #모든 sheet이름 출력

#sheet 복사
new_ws["A1"]="Test"
target=wb.copy_worksheet(new_ws)
target.title="Copied sheet"
wb.save("sample.xlsx")
wb.close()